### ISSUE TITLE
Question about the mutual NN matcher

### ISSUE THREAD

**Issue by ShrutheeshIR** [mihaidusmanu/torch-feature-matching#1]
Hello,
Thanks for sharing the implementations! I was wondering if the mutual NN matcher is unique in nature. I.e. will every keypoint (descriptor) on the left hand side uniquely match with the descriptors on the right? Or can multiple keypoints match with the same descriptor on the right? 
If so, can you point out which part of the code enforces this particular behaviour?

Thanks!

**Comment by mihaidusmanu** [comment]
Hello. When using the mutual NN matcher, every descriptor on one side will have at most one matching descriptor on the other side. It is possible that a descriptor doesn't have a match in case the mutual NN check is failed. The check is done in L12
https://github.com/mihaidusmanu/torch-feature-matching/blob/4bb6c4a8172af4b28834ffb115c666ae021226ef/feature_matchers.py#L12

**Comment by ShrutheeshIR** [comment]
Hello. Oh, that makes sense.
Is it possible for me to have a mutual NN matcher, along with a threshold value. i.e. I wish to retain only those matches with similarity greater than 0.90.

**Comment by mihaidusmanu** [comment]
Yes, of course. You will need to combine the conditions in lines 12 and 55 using a logical and:
```
mask = ((nn_sim >= threshold) & (ids1 == nn21[nn12]))  # PyTorch 1.2+

mask = torch.min((nn_sim >= threshold), (ids1 == nn21[nn12]))  # PyTorch <1.2
```

**Comment by ShrutheeshIR** [comment]
Thanks a ton!
